// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_HYPERDB_HYPERDB_H_
#define FLATBUFFERS_GENERATED_HYPERDB_HYPERDB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace HyperDB {

struct Int8Column;
struct Int8ColumnBuilder;

struct Int16Column;
struct Int16ColumnBuilder;

struct Int32Column;
struct Int32ColumnBuilder;

struct Int64Column;
struct Int64ColumnBuilder;

struct UInt8Column;
struct UInt8ColumnBuilder;

struct UInt16Column;
struct UInt16ColumnBuilder;

struct UInt32Column;
struct UInt32ColumnBuilder;

struct UInt64Column;
struct UInt64ColumnBuilder;

struct Float32Column;
struct Float32ColumnBuilder;

struct Float64Column;
struct Float64ColumnBuilder;

struct BoolColumn;
struct BoolColumnBuilder;

struct StringColumn;
struct StringColumnBuilder;

struct BytesColumn;
struct BytesColumnBuilder;

struct Column;
struct ColumnBuilder;

struct Table;
struct TableBuilder;

struct Database;
struct DatabaseBuilder;

enum ColumnType : int8_t {
  ColumnType_Int8 = 0,
  ColumnType_Int16 = 1,
  ColumnType_Int32 = 2,
  ColumnType_Int64 = 3,
  ColumnType_UInt8 = 4,
  ColumnType_UInt16 = 5,
  ColumnType_UInt32 = 6,
  ColumnType_UInt64 = 7,
  ColumnType_Float32 = 8,
  ColumnType_Float64 = 9,
  ColumnType_Bool = 10,
  ColumnType_String = 11,
  ColumnType_Bytes = 12,
  ColumnType_MIN = ColumnType_Int8,
  ColumnType_MAX = ColumnType_Bytes
};

inline const ColumnType (&EnumValuesColumnType())[13] {
  static const ColumnType values[] = {
    ColumnType_Int8,
    ColumnType_Int16,
    ColumnType_Int32,
    ColumnType_Int64,
    ColumnType_UInt8,
    ColumnType_UInt16,
    ColumnType_UInt32,
    ColumnType_UInt64,
    ColumnType_Float32,
    ColumnType_Float64,
    ColumnType_Bool,
    ColumnType_String,
    ColumnType_Bytes
  };
  return values;
}

inline const char * const *EnumNamesColumnType() {
  static const char * const names[14] = {
    "Int8",
    "Int16",
    "Int32",
    "Int64",
    "UInt8",
    "UInt16",
    "UInt32",
    "UInt64",
    "Float32",
    "Float64",
    "Bool",
    "String",
    "Bytes",
    nullptr
  };
  return names;
}

inline const char *EnumNameColumnType(ColumnType e) {
  if (::flatbuffers::IsOutRange(e, ColumnType_Int8, ColumnType_Bytes)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesColumnType()[index];
}

enum ColumnData : uint8_t {
  ColumnData_NONE = 0,
  ColumnData_Int8Column = 1,
  ColumnData_Int16Column = 2,
  ColumnData_Int32Column = 3,
  ColumnData_Int64Column = 4,
  ColumnData_UInt8Column = 5,
  ColumnData_UInt16Column = 6,
  ColumnData_UInt32Column = 7,
  ColumnData_UInt64Column = 8,
  ColumnData_Float32Column = 9,
  ColumnData_Float64Column = 10,
  ColumnData_BoolColumn = 11,
  ColumnData_StringColumn = 12,
  ColumnData_BytesColumn = 13,
  ColumnData_MIN = ColumnData_NONE,
  ColumnData_MAX = ColumnData_BytesColumn
};

inline const ColumnData (&EnumValuesColumnData())[14] {
  static const ColumnData values[] = {
    ColumnData_NONE,
    ColumnData_Int8Column,
    ColumnData_Int16Column,
    ColumnData_Int32Column,
    ColumnData_Int64Column,
    ColumnData_UInt8Column,
    ColumnData_UInt16Column,
    ColumnData_UInt32Column,
    ColumnData_UInt64Column,
    ColumnData_Float32Column,
    ColumnData_Float64Column,
    ColumnData_BoolColumn,
    ColumnData_StringColumn,
    ColumnData_BytesColumn
  };
  return values;
}

inline const char * const *EnumNamesColumnData() {
  static const char * const names[15] = {
    "NONE",
    "Int8Column",
    "Int16Column",
    "Int32Column",
    "Int64Column",
    "UInt8Column",
    "UInt16Column",
    "UInt32Column",
    "UInt64Column",
    "Float32Column",
    "Float64Column",
    "BoolColumn",
    "StringColumn",
    "BytesColumn",
    nullptr
  };
  return names;
}

inline const char *EnumNameColumnData(ColumnData e) {
  if (::flatbuffers::IsOutRange(e, ColumnData_NONE, ColumnData_BytesColumn)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesColumnData()[index];
}

template<typename T> struct ColumnDataTraits {
  static const ColumnData enum_value = ColumnData_NONE;
};

template<> struct ColumnDataTraits<HyperDB::Int8Column> {
  static const ColumnData enum_value = ColumnData_Int8Column;
};

template<> struct ColumnDataTraits<HyperDB::Int16Column> {
  static const ColumnData enum_value = ColumnData_Int16Column;
};

template<> struct ColumnDataTraits<HyperDB::Int32Column> {
  static const ColumnData enum_value = ColumnData_Int32Column;
};

template<> struct ColumnDataTraits<HyperDB::Int64Column> {
  static const ColumnData enum_value = ColumnData_Int64Column;
};

template<> struct ColumnDataTraits<HyperDB::UInt8Column> {
  static const ColumnData enum_value = ColumnData_UInt8Column;
};

template<> struct ColumnDataTraits<HyperDB::UInt16Column> {
  static const ColumnData enum_value = ColumnData_UInt16Column;
};

template<> struct ColumnDataTraits<HyperDB::UInt32Column> {
  static const ColumnData enum_value = ColumnData_UInt32Column;
};

template<> struct ColumnDataTraits<HyperDB::UInt64Column> {
  static const ColumnData enum_value = ColumnData_UInt64Column;
};

template<> struct ColumnDataTraits<HyperDB::Float32Column> {
  static const ColumnData enum_value = ColumnData_Float32Column;
};

template<> struct ColumnDataTraits<HyperDB::Float64Column> {
  static const ColumnData enum_value = ColumnData_Float64Column;
};

template<> struct ColumnDataTraits<HyperDB::BoolColumn> {
  static const ColumnData enum_value = ColumnData_BoolColumn;
};

template<> struct ColumnDataTraits<HyperDB::StringColumn> {
  static const ColumnData enum_value = ColumnData_StringColumn;
};

template<> struct ColumnDataTraits<HyperDB::BytesColumn> {
  static const ColumnData enum_value = ColumnData_BytesColumn;
};

template <bool B = false>
bool VerifyColumnData(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, ColumnData type);
template <bool B = false>
bool VerifyColumnDataVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct Int8Column FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Int8ColumnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<int8_t> *values() const {
    return GetPointer<const ::flatbuffers::Vector<int8_t> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct Int8ColumnBuilder {
  typedef Int8Column Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<int8_t>> values) {
    fbb_.AddOffset(Int8Column::VT_VALUES, values);
  }
  explicit Int8ColumnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Int8Column> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Int8Column>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Int8Column> CreateInt8Column(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<int8_t>> values = 0) {
  Int8ColumnBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Int8Column> CreateInt8ColumnDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int8_t> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<int8_t>(*values) : 0;
  return HyperDB::CreateInt8Column(
      _fbb,
      values__);
}

struct Int16Column FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Int16ColumnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<int16_t> *values() const {
    return GetPointer<const ::flatbuffers::Vector<int16_t> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct Int16ColumnBuilder {
  typedef Int16Column Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<int16_t>> values) {
    fbb_.AddOffset(Int16Column::VT_VALUES, values);
  }
  explicit Int16ColumnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Int16Column> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Int16Column>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Int16Column> CreateInt16Column(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<int16_t>> values = 0) {
  Int16ColumnBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Int16Column> CreateInt16ColumnDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int16_t> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<int16_t>(*values) : 0;
  return HyperDB::CreateInt16Column(
      _fbb,
      values__);
}

struct Int32Column FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Int32ColumnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<int32_t> *values() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct Int32ColumnBuilder {
  typedef Int32Column Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> values) {
    fbb_.AddOffset(Int32Column::VT_VALUES, values);
  }
  explicit Int32ColumnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Int32Column> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Int32Column>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Int32Column> CreateInt32Column(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> values = 0) {
  Int32ColumnBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Int32Column> CreateInt32ColumnDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int32_t> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<int32_t>(*values) : 0;
  return HyperDB::CreateInt32Column(
      _fbb,
      values__);
}

struct Int64Column FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Int64ColumnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<int64_t> *values() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct Int64ColumnBuilder {
  typedef Int64Column Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> values) {
    fbb_.AddOffset(Int64Column::VT_VALUES, values);
  }
  explicit Int64ColumnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Int64Column> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Int64Column>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Int64Column> CreateInt64Column(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> values = 0) {
  Int64ColumnBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Int64Column> CreateInt64ColumnDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int64_t> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<int64_t>(*values) : 0;
  return HyperDB::CreateInt64Column(
      _fbb,
      values__);
}

struct UInt8Column FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UInt8ColumnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<uint8_t> *values() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct UInt8ColumnBuilder {
  typedef UInt8Column Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> values) {
    fbb_.AddOffset(UInt8Column::VT_VALUES, values);
  }
  explicit UInt8ColumnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UInt8Column> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UInt8Column>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UInt8Column> CreateUInt8Column(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> values = 0) {
  UInt8ColumnBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UInt8Column> CreateUInt8ColumnDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<uint8_t>(*values) : 0;
  return HyperDB::CreateUInt8Column(
      _fbb,
      values__);
}

struct UInt16Column FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UInt16ColumnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<uint16_t> *values() const {
    return GetPointer<const ::flatbuffers::Vector<uint16_t> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct UInt16ColumnBuilder {
  typedef UInt16Column Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> values) {
    fbb_.AddOffset(UInt16Column::VT_VALUES, values);
  }
  explicit UInt16ColumnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UInt16Column> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UInt16Column>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UInt16Column> CreateUInt16Column(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> values = 0) {
  UInt16ColumnBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UInt16Column> CreateUInt16ColumnDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint16_t> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<uint16_t>(*values) : 0;
  return HyperDB::CreateUInt16Column(
      _fbb,
      values__);
}

struct UInt32Column FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UInt32ColumnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<uint32_t> *values() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct UInt32ColumnBuilder {
  typedef UInt32Column Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> values) {
    fbb_.AddOffset(UInt32Column::VT_VALUES, values);
  }
  explicit UInt32ColumnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UInt32Column> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UInt32Column>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UInt32Column> CreateUInt32Column(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> values = 0) {
  UInt32ColumnBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UInt32Column> CreateUInt32ColumnDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint32_t> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<uint32_t>(*values) : 0;
  return HyperDB::CreateUInt32Column(
      _fbb,
      values__);
}

struct UInt64Column FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UInt64ColumnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<uint64_t> *values() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct UInt64ColumnBuilder {
  typedef UInt64Column Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> values) {
    fbb_.AddOffset(UInt64Column::VT_VALUES, values);
  }
  explicit UInt64ColumnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UInt64Column> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UInt64Column>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UInt64Column> CreateUInt64Column(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> values = 0) {
  UInt64ColumnBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UInt64Column> CreateUInt64ColumnDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint64_t> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<uint64_t>(*values) : 0;
  return HyperDB::CreateUInt64Column(
      _fbb,
      values__);
}

struct Float32Column FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Float32ColumnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<float> *values() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct Float32ColumnBuilder {
  typedef Float32Column Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<float>> values) {
    fbb_.AddOffset(Float32Column::VT_VALUES, values);
  }
  explicit Float32ColumnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Float32Column> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Float32Column>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Float32Column> CreateFloat32Column(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> values = 0) {
  Float32ColumnBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Float32Column> CreateFloat32ColumnDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<float>(*values) : 0;
  return HyperDB::CreateFloat32Column(
      _fbb,
      values__);
}

struct Float64Column FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Float64ColumnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<double> *values() const {
    return GetPointer<const ::flatbuffers::Vector<double> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct Float64ColumnBuilder {
  typedef Float64Column Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<double>> values) {
    fbb_.AddOffset(Float64Column::VT_VALUES, values);
  }
  explicit Float64ColumnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Float64Column> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Float64Column>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Float64Column> CreateFloat64Column(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> values = 0) {
  Float64ColumnBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Float64Column> CreateFloat64ColumnDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<double> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<double>(*values) : 0;
  return HyperDB::CreateFloat64Column(
      _fbb,
      values__);
}

struct BoolColumn FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BoolColumnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<uint8_t> *values() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct BoolColumnBuilder {
  typedef BoolColumn Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> values) {
    fbb_.AddOffset(BoolColumn::VT_VALUES, values);
  }
  explicit BoolColumnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BoolColumn> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BoolColumn>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BoolColumn> CreateBoolColumn(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> values = 0) {
  BoolColumnBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BoolColumn> CreateBoolColumnDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<uint8_t>(*values) : 0;
  return HyperDB::CreateBoolColumn(
      _fbb,
      values__);
}

struct StringColumn FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StringColumnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.VerifyVectorOfStrings(values()) &&
           verifier.EndTable();
  }
};

struct StringColumnBuilder {
  typedef StringColumn Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> values) {
    fbb_.AddOffset(StringColumn::VT_VALUES, values);
  }
  explicit StringColumnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StringColumn> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StringColumn>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StringColumn> CreateStringColumn(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> values = 0) {
  StringColumnBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StringColumn> CreateStringColumnDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*values) : 0;
  return HyperDB::CreateStringColumn(
      _fbb,
      values__);
}

struct BytesColumn FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BytesColumnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.VerifyVectorOfStrings(values()) &&
           verifier.EndTable();
  }
};

struct BytesColumnBuilder {
  typedef BytesColumn Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> values) {
    fbb_.AddOffset(BytesColumn::VT_VALUES, values);
  }
  explicit BytesColumnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BytesColumn> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BytesColumn>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BytesColumn> CreateBytesColumn(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> values = 0) {
  BytesColumnBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BytesColumn> CreateBytesColumnDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*values) : 0;
  return HyperDB::CreateBytesColumn(
      _fbb,
      values__);
}

struct Column FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ColumnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_TYPE = 6,
    VT_DATA_TYPE = 8,
    VT_DATA = 10
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  HyperDB::ColumnType type() const {
    return static_cast<HyperDB::ColumnType>(GetField<int8_t>(VT_TYPE, 0));
  }
  HyperDB::ColumnData data_type() const {
    return static_cast<HyperDB::ColumnData>(GetField<uint8_t>(VT_DATA_TYPE, 0));
  }
  const void *data() const {
    return GetPointer<const void *>(VT_DATA);
  }
  template<typename T> const T *data_as() const;
  const HyperDB::Int8Column *data_as_Int8Column() const {
    return data_type() == HyperDB::ColumnData_Int8Column ? static_cast<const HyperDB::Int8Column *>(data()) : nullptr;
  }
  const HyperDB::Int16Column *data_as_Int16Column() const {
    return data_type() == HyperDB::ColumnData_Int16Column ? static_cast<const HyperDB::Int16Column *>(data()) : nullptr;
  }
  const HyperDB::Int32Column *data_as_Int32Column() const {
    return data_type() == HyperDB::ColumnData_Int32Column ? static_cast<const HyperDB::Int32Column *>(data()) : nullptr;
  }
  const HyperDB::Int64Column *data_as_Int64Column() const {
    return data_type() == HyperDB::ColumnData_Int64Column ? static_cast<const HyperDB::Int64Column *>(data()) : nullptr;
  }
  const HyperDB::UInt8Column *data_as_UInt8Column() const {
    return data_type() == HyperDB::ColumnData_UInt8Column ? static_cast<const HyperDB::UInt8Column *>(data()) : nullptr;
  }
  const HyperDB::UInt16Column *data_as_UInt16Column() const {
    return data_type() == HyperDB::ColumnData_UInt16Column ? static_cast<const HyperDB::UInt16Column *>(data()) : nullptr;
  }
  const HyperDB::UInt32Column *data_as_UInt32Column() const {
    return data_type() == HyperDB::ColumnData_UInt32Column ? static_cast<const HyperDB::UInt32Column *>(data()) : nullptr;
  }
  const HyperDB::UInt64Column *data_as_UInt64Column() const {
    return data_type() == HyperDB::ColumnData_UInt64Column ? static_cast<const HyperDB::UInt64Column *>(data()) : nullptr;
  }
  const HyperDB::Float32Column *data_as_Float32Column() const {
    return data_type() == HyperDB::ColumnData_Float32Column ? static_cast<const HyperDB::Float32Column *>(data()) : nullptr;
  }
  const HyperDB::Float64Column *data_as_Float64Column() const {
    return data_type() == HyperDB::ColumnData_Float64Column ? static_cast<const HyperDB::Float64Column *>(data()) : nullptr;
  }
  const HyperDB::BoolColumn *data_as_BoolColumn() const {
    return data_type() == HyperDB::ColumnData_BoolColumn ? static_cast<const HyperDB::BoolColumn *>(data()) : nullptr;
  }
  const HyperDB::StringColumn *data_as_StringColumn() const {
    return data_type() == HyperDB::ColumnData_StringColumn ? static_cast<const HyperDB::StringColumn *>(data()) : nullptr;
  }
  const HyperDB::BytesColumn *data_as_BytesColumn() const {
    return data_type() == HyperDB::ColumnData_BytesColumn ? static_cast<const HyperDB::BytesColumn *>(data()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_DATA_TYPE, 1) &&
           VerifyOffset(verifier, VT_DATA) &&
           VerifyColumnData(verifier, data(), data_type()) &&
           verifier.EndTable();
  }
};

template<> inline const HyperDB::Int8Column *Column::data_as<HyperDB::Int8Column>() const {
  return data_as_Int8Column();
}

template<> inline const HyperDB::Int16Column *Column::data_as<HyperDB::Int16Column>() const {
  return data_as_Int16Column();
}

template<> inline const HyperDB::Int32Column *Column::data_as<HyperDB::Int32Column>() const {
  return data_as_Int32Column();
}

template<> inline const HyperDB::Int64Column *Column::data_as<HyperDB::Int64Column>() const {
  return data_as_Int64Column();
}

template<> inline const HyperDB::UInt8Column *Column::data_as<HyperDB::UInt8Column>() const {
  return data_as_UInt8Column();
}

template<> inline const HyperDB::UInt16Column *Column::data_as<HyperDB::UInt16Column>() const {
  return data_as_UInt16Column();
}

template<> inline const HyperDB::UInt32Column *Column::data_as<HyperDB::UInt32Column>() const {
  return data_as_UInt32Column();
}

template<> inline const HyperDB::UInt64Column *Column::data_as<HyperDB::UInt64Column>() const {
  return data_as_UInt64Column();
}

template<> inline const HyperDB::Float32Column *Column::data_as<HyperDB::Float32Column>() const {
  return data_as_Float32Column();
}

template<> inline const HyperDB::Float64Column *Column::data_as<HyperDB::Float64Column>() const {
  return data_as_Float64Column();
}

template<> inline const HyperDB::BoolColumn *Column::data_as<HyperDB::BoolColumn>() const {
  return data_as_BoolColumn();
}

template<> inline const HyperDB::StringColumn *Column::data_as<HyperDB::StringColumn>() const {
  return data_as_StringColumn();
}

template<> inline const HyperDB::BytesColumn *Column::data_as<HyperDB::BytesColumn>() const {
  return data_as_BytesColumn();
}

struct ColumnBuilder {
  typedef Column Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Column::VT_NAME, name);
  }
  void add_type(HyperDB::ColumnType type) {
    fbb_.AddElement<int8_t>(Column::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_data_type(HyperDB::ColumnData data_type) {
    fbb_.AddElement<uint8_t>(Column::VT_DATA_TYPE, static_cast<uint8_t>(data_type), 0);
  }
  void add_data(::flatbuffers::Offset<void> data) {
    fbb_.AddOffset(Column::VT_DATA, data);
  }
  explicit ColumnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Column> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Column>(end);
    fbb_.Required(o, Column::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<Column> CreateColumn(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    HyperDB::ColumnType type = HyperDB::ColumnType_Int8,
    HyperDB::ColumnData data_type = HyperDB::ColumnData_NONE,
    ::flatbuffers::Offset<void> data = 0) {
  ColumnBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_name(name);
  builder_.add_data_type(data_type);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Column> CreateColumnDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    HyperDB::ColumnType type = HyperDB::ColumnType_Int8,
    HyperDB::ColumnData data_type = HyperDB::ColumnData_NONE,
    ::flatbuffers::Offset<void> data = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return HyperDB::CreateColumn(
      _fbb,
      name__,
      type,
      data_type,
      data);
}

struct Table FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TableBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_COLUMNS = 6,
    VT_ROW_COUNT = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<HyperDB::Column>> *columns() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<HyperDB::Column>> *>(VT_COLUMNS);
  }
  uint64_t row_count() const {
    return GetField<uint64_t>(VT_ROW_COUNT, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_COLUMNS) &&
           verifier.VerifyVector(columns()) &&
           verifier.VerifyVectorOfTables(columns()) &&
           VerifyField<uint64_t>(verifier, VT_ROW_COUNT, 8) &&
           verifier.EndTable();
  }
};

struct TableBuilder {
  typedef Table Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Table::VT_NAME, name);
  }
  void add_columns(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<HyperDB::Column>>> columns) {
    fbb_.AddOffset(Table::VT_COLUMNS, columns);
  }
  void add_row_count(uint64_t row_count) {
    fbb_.AddElement<uint64_t>(Table::VT_ROW_COUNT, row_count, 0);
  }
  explicit TableBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Table> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Table>(end);
    fbb_.Required(o, Table::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<Table> CreateTable(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<HyperDB::Column>>> columns = 0,
    uint64_t row_count = 0) {
  TableBuilder builder_(_fbb);
  builder_.add_row_count(row_count);
  builder_.add_columns(columns);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Table> CreateTableDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const std::vector<::flatbuffers::Offset<HyperDB::Column>> *columns = nullptr,
    uint64_t row_count = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto columns__ = columns ? _fbb.CreateVector<::flatbuffers::Offset<HyperDB::Column>>(*columns) : 0;
  return HyperDB::CreateTable(
      _fbb,
      name__,
      columns__,
      row_count);
}

struct Database FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DatabaseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_TABLES = 6,
    VT_VERSION = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<HyperDB::Table>> *tables() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<HyperDB::Table>> *>(VT_TABLES);
  }
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 1);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_TABLES) &&
           verifier.VerifyVector(tables()) &&
           verifier.VerifyVectorOfTables(tables()) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           verifier.EndTable();
  }
};

struct DatabaseBuilder {
  typedef Database Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Database::VT_NAME, name);
  }
  void add_tables(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<HyperDB::Table>>> tables) {
    fbb_.AddOffset(Database::VT_TABLES, tables);
  }
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(Database::VT_VERSION, version, 1);
  }
  explicit DatabaseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Database> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Database>(end);
    fbb_.Required(o, Database::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<Database> CreateDatabase(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<HyperDB::Table>>> tables = 0,
    uint32_t version = 1) {
  DatabaseBuilder builder_(_fbb);
  builder_.add_version(version);
  builder_.add_tables(tables);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Database> CreateDatabaseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const std::vector<::flatbuffers::Offset<HyperDB::Table>> *tables = nullptr,
    uint32_t version = 1) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto tables__ = tables ? _fbb.CreateVector<::flatbuffers::Offset<HyperDB::Table>>(*tables) : 0;
  return HyperDB::CreateDatabase(
      _fbb,
      name__,
      tables__,
      version);
}

template <bool B>
inline bool VerifyColumnData(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, ColumnData type) {
  switch (type) {
    case ColumnData_NONE: {
      return true;
    }
    case ColumnData_Int8Column: {
      auto ptr = reinterpret_cast<const HyperDB::Int8Column *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ColumnData_Int16Column: {
      auto ptr = reinterpret_cast<const HyperDB::Int16Column *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ColumnData_Int32Column: {
      auto ptr = reinterpret_cast<const HyperDB::Int32Column *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ColumnData_Int64Column: {
      auto ptr = reinterpret_cast<const HyperDB::Int64Column *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ColumnData_UInt8Column: {
      auto ptr = reinterpret_cast<const HyperDB::UInt8Column *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ColumnData_UInt16Column: {
      auto ptr = reinterpret_cast<const HyperDB::UInt16Column *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ColumnData_UInt32Column: {
      auto ptr = reinterpret_cast<const HyperDB::UInt32Column *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ColumnData_UInt64Column: {
      auto ptr = reinterpret_cast<const HyperDB::UInt64Column *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ColumnData_Float32Column: {
      auto ptr = reinterpret_cast<const HyperDB::Float32Column *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ColumnData_Float64Column: {
      auto ptr = reinterpret_cast<const HyperDB::Float64Column *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ColumnData_BoolColumn: {
      auto ptr = reinterpret_cast<const HyperDB::BoolColumn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ColumnData_StringColumn: {
      auto ptr = reinterpret_cast<const HyperDB::StringColumn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ColumnData_BytesColumn: {
      auto ptr = reinterpret_cast<const HyperDB::BytesColumn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyColumnDataVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyColumnData(
        verifier,  values->Get(i), types->GetEnum<ColumnData>(i))) {
      return false;
    }
  }
  return true;
}

inline const HyperDB::Database *GetDatabase(const void *buf) {
  return ::flatbuffers::GetRoot<HyperDB::Database>(buf);
}

inline const HyperDB::Database *GetSizePrefixedDatabase(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<HyperDB::Database>(buf);
}

inline const char *DatabaseIdentifier() {
  return "HYDB";
}

inline bool DatabaseBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, DatabaseIdentifier());
}

inline bool SizePrefixedDatabaseBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, DatabaseIdentifier(), true);
}

template <bool B = false>
inline bool VerifyDatabaseBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<HyperDB::Database>(DatabaseIdentifier());
}

template <bool B = false>
inline bool VerifySizePrefixedDatabaseBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<HyperDB::Database>(DatabaseIdentifier());
}

inline const char *DatabaseExtension() {
  return "db";
}

inline void FinishDatabaseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<HyperDB::Database> root) {
  fbb.Finish(root, DatabaseIdentifier());
}

inline void FinishSizePrefixedDatabaseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<HyperDB::Database> root) {
  fbb.FinishSizePrefixed(root, DatabaseIdentifier());
}

}  // namespace HyperDB

#endif  // FLATBUFFERS_GENERATED_HYPERDB_HYPERDB_H_
